#!/bin/bash

# =========================================================
# VPS TCP Optimization Script for Debian 13 (Kernel 6.x+)
# Author: Gemini
# Description: Enables BBR, optimizes TCP buffers, handles, and timeouts.
# =========================================================

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
PLAIN='\033[0m'

# 检查是否为 Root 用户
if [[ $EUID -ne 0 ]]; then
   echo -e "${RED}Error: 本脚本必须以 Root 权限运行！${PLAIN}" 
   echo -e "请使用 'sudo -i' 切换到 Root 用户后再试。"
   exit 1
fi

echo -e "${GREEN}==========================================================${PLAIN}"
echo -e "${GREEN}      Debian 13 (Trixie) VPS TCP 极速调优脚本      ${PLAIN}"
echo -e "${GREEN}==========================================================${PLAIN}"

# 1. 检查系统版本与内核
OS_NAME=$(grep -oP '(?<=^NAME=").*(?=")' /etc/os-release)
KERNEL_VER=$(uname -r)
echo -e "当前系统: ${YELLOW}$OS_NAME${PLAIN}"
echo -e "内核版本: ${YELLOW}$KERNEL_VER${PLAIN}"

# 简单判断是否适合 (Debian 13 通常是 6.x 内核)
if [[ "${KERNEL_VER}" != 6.* ]] && [[ "${KERNEL_VER}" != 5.* ]]; then
    echo -e "${YELLOW}警告: 检测到内核版本非 5.x/6.x，建议升级内核以获得 BBR 最佳性能。${PLAIN}"
    read -p "是否继续？(y/n): " confirm
    [[ $confirm != "y" ]] && exit 1
fi

echo -e "\n${GREEN}[1/4] 正在备份当前 Sysctl 配置...${PLAIN}"
cp /etc/sysctl.conf /etc/sysctl.conf.bak.$(date +%F-%T)
echo -e "备份已保存至: /etc/sysctl.conf.bak.$(date +%F-%T)"

echo -e "\n${GREEN}[2/4] 正在应用 TCP 优化参数...${PLAIN}"

# 定义优化参数文件路径 (使用独立文件，避免污染主配置文件)
SYSCTL_FILE="/etc/sysctl.d/99-vps-tuning.conf"

cat > "$SYSCTL_FILE" << EOF
# =================================================================
# VPS TCP Tuning for Debian 13 / Kernel 6.x
# Generated by Optimization Script
# =================================================================

# --- 1. BBR 拥塞控制 (核心优化) ---
# 使用 fq 作为包调度程序 (BBR 的最佳拍档)
net.core.default_qdisc = fq
# 开启 BBR 拥塞控制算法
net.ipv4.tcp_congestion_control = bbr

# --- 2. TCP 缓冲区与窗口优化 (提升吞吐量) ---
# 增加读写缓冲区大小 (适配 1G/10G 端口)
net.core.rmem_max = 33554432
net.core.wmem_max = 33554432
net.core.rmem_default = 1048576
net.core.wmem_default = 1048576
# 自动调整 TCP 缓冲区 (Min Default Max)
net.ipv4.tcp_rmem = 16384 1048576 33554432
net.ipv4.tcp_wmem = 16384 1048576 33554432
# 开启窗口缩放 (RFC 1323)
net.ipv4.tcp_window_scaling = 1

# --- 3. 连接与队列优化 (抗高并发) ---
# 增加系统最大文件打开数
fs.file-max = 2097152
# 增加网卡积压队列长度 (防止丢包)
net.core.netdev_max_backlog = 32768
# 增加半连接队列长度 (抗 SYN Flood)
net.ipv4.tcp_max_syn_backlog = 16384
# 增加全连接队列长度
net.core.somaxconn = 32768

# --- 4. Time-Wait 与 连接重用 ---
# 允许重用 TIME_WAIT 状态的 socket (对 Web Server 有利)
net.ipv4.tcp_tw_reuse = 1
# 缩短 Keepalive 探测时间 (更快发现死连接)
net.ipv4.tcp_keepalive_time = 600
net.ipv4.tcp_keepalive_intvl = 15
net.ipv4.tcp_keepalive_probes = 5
# 缩短 FIN_WAIT2 超时时间
net.ipv4.tcp_fin_timeout = 30

# --- 5. 其他优化 ---
# 开启 TCP Fast Open (降低延迟，需要服务端/客户端支持)
net.ipv4.tcp_fastopen = 3
# 禁用慢启动重启 (SSR)，改善长连接性能
net.ipv4.tcp_slow_start_after_idle = 0
# IP 转发 (如果是做网关/梯子需要开启，普通 VPS 可选，默认开启通用性更好)
net.ipv4.ip_forward = 1
EOF

echo -e "\n${GREEN}[3/4] 正在加载新配置...${PLAIN}"
# 刷新 sysctl
sysctl --system > /dev/null 2>&1

# 增加 limits (文件描述符限制)
if ! grep -q "soft nofile 1000000" /etc/security/limits.conf; then
    echo "* soft nofile 1000000" >> /etc/security/limits.conf
    echo "* hard nofile 1000000" >> /etc/security/limits.conf
    echo "root soft nofile 1000000" >> /etc/security/limits.conf
    echo "root hard nofile 1000000" >> /etc/security/limits.conf
    echo -e "已更新 /etc/security/limits.conf 文件描述符限制。"
fi

echo -e "\n${GREEN}[4/4] 验证优化结果...${PLAIN}"

# 验证 BBR 是否开启
CURRENT_ALGO=$(sysctl net.ipv4.tcp_congestion_control | awk '{print $3}')
CURRENT_QDISC=$(sysctl net.core.default_qdisc | awk '{print $3}')

if [[ "$CURRENT_ALGO" == "bbr" ]] && [[ "$CURRENT_QDISC" == "fq" ]]; then
    echo -e "BBR 状态: ${GREEN}成功开启 (bbr + fq)${PLAIN}"
else
    echo -e "BBR 状态: ${RED}开启失败${PLAIN} (当前: $CURRENT_ALGO + $CURRENT_QDISC)"
    echo -e "提示: 如果失败，请重启 VPS 后再次检查。"
fi

echo -e "\n${GREEN}==========================================================${PLAIN}"
echo -e "${GREEN}      优化完成！建议重启一次 VPS 以确保所有设置生效。      ${PLAIN}"
echo -e "${GREEN}==========================================================${PLAIN}"
